### ISSUE TITLE
Why did you stop?

### ISSUE THREAD

**Issue by AvocadoKings** [Ombrelin/five-years-plan#1]
Not really an issue but i'm checking up on you. How are you?
I think this project has potential. It's a shame you stopped. I would make a fork but i don't have enough experience in c#.

**Comment by Ombrelin** [comment]
Hi @AvocadoKings,
thanks a lot for your interest and support :smiley: 
I did not have a lot of free time to work on this in the previous months, and I've not played Satisfactory in a while. But with 1.0 of the game, which I am eager to play, and the fact I'll have some vacation in November, I will continue working on the project, to at least try to get it usable for basic use cases :+1:

**Comment by Ombrelin** [comment]
My ideal roadmap would be :  implement buildings and recipes for tiers 1 so people can start using the software and give some feedback, and then follow up on that feedback. Then do the same for each tier.

**Comment by AvocadoKings** [comment]
I am so glad to hear that. Don't overwork yourself!

**Comment by Ombrelin** [comment]
Hi @AvocadoKings,
hope you're doing well :smiley: 
I published a release for a first version with T0 & T1 buildings, it's provided through a windows installer for ease of use.
It's still very rough but shoudl be 
Feel free to test it and provide any feedback you would have :+1:
